package com.zestflow.collector.jdbc.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.zestflow.collector.jdbc.entity.ChainEventPO;
import com.zestflow.common.protocol.EventQuery;
import com.zestflow.common.protocol.EventStatsQuery;
import com.zestflow.common.protocol.LogAnalyticsQuery;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;
import java.util.Map;

/**
 * 链执行事件 Mapper
 */
@Mapper
public interface ChainEventMapper extends BaseMapper<ChainEventPO> {

    /**
     * 批量插入（INSERT IGNORE 保证幂等性）
     */
    @Insert({
            "<script>",
            "INSERT IGNORE INTO chain_event(event_id, event_type, execution_id, chain_id, chain_name,",
            "  node_id, node_name, executor_id, app_code, app_name, tenant_id,",
            "  cost_ms, status, timestamp, metadata, create_time)",
            "VALUES ",
            "<foreach collection='list' item='e' separator=','>",
            "  (#{e.eventId}, #{e.eventType}, #{e.executionId}, #{e.chainId}, #{e.chainName},",
            "   #{e.nodeId}, #{e.nodeName}, #{e.executorId}, #{e.appCode}, #{e.appName}, #{e.tenantId},",
            "   #{e.costMs}, #{e.status}, #{e.timestamp}, #{e.metadata}, NOW())",
            "</foreach>",
            "</script>"
    })
    int insertIgnoreBatch(@Param("list") List<ChainEventPO> list);

    /**
     * 查询执行轨迹列表（GROUP BY execution_id）
     */
    @Select({
            "<script>",
            "SELECT e.execution_id AS executionId,",
            "  ANY_VALUE(e.chain_id) AS chainId,",
            "  ANY_VALUE(e.chain_name) AS chainName,",
            "  ANY_VALUE(e.executor_id) AS executorId,",
            "  ANY_VALUE(e.app_name) AS appName,",
            "  ANY_VALUE(e.app_code) AS appCode,",
            "  MIN(e.timestamp) AS timestamp,",
            "  MAX(CASE WHEN e.event_type IN ('CHAIN_COMPLETED','CHAIN_FAILED','CHAIN_TIMEOUT')",
            "       THEN e.cost_ms ELSE NULL END) AS costMs,",
            "  MAX(CASE WHEN e.event_type IN ('CHAIN_FAILED','CHAIN_TIMEOUT') THEN 0",
            "       WHEN e.event_type = 'CHAIN_COMPLETED' THEN 1 ELSE -1 END) AS status,",
            "  COUNT(*) AS eventCount,",
            "  COUNT(DISTINCT CASE WHEN e.node_id IS NOT NULL AND e.node_id != ''",
            "       AND e.event_type LIKE 'NODE_%' THEN e.node_id END) AS nodeCount,",
            "  COUNT(DISTINCT CASE WHEN e.node_id IS NOT NULL AND e.node_id != ''",
            "       AND e.event_type IN ('NODE_COMPLETED','NODE_FALLBACK_SUCCESS') THEN e.node_id END) AS successCount,",
            "  COUNT(DISTINCT CASE WHEN e.node_id IS NOT NULL AND e.node_id != ''",
            "       AND e.event_type IN ('NODE_FAILED','NODE_FALLBACK_FAILED') THEN e.node_id END) AS failedCount",
            "FROM chain_event e",
            "WHERE e.execution_id IS NOT NULL",
            "<if test='query.tenantId != null'>",
            "  AND e.tenant_id = #{query.tenantId}",
            "</if>",
            "<if test='query.executionId != null and query.executionId != \"\"'>",
            "  AND e.execution_id = #{query.executionId}",
            "</if>",
            "<if test='query.chainId != null and query.chainId != \"\"'>",
            "  AND e.chain_id = #{query.chainId}",
            "</if>",
            "<if test='query.chainName != null and query.chainName != \"\"'>",
            "  AND e.chain_name LIKE CONCAT('%', #{query.chainName}, '%')",
            "</if>",
            "<if test='query.executorId != null and query.executorId != \"\"'>",
            "  AND e.executor_id = #{query.executorId}",
            "</if>",
            "<if test='query.appCode != null and query.appCode != \"\"'>",
            "  AND e.app_code = #{query.appCode}",
            "</if>",
            "<if test='query.appName != null and query.appName != \"\"'>",
            "  AND e.app_name = #{query.appName}",
            "</if>",
            "<if test='query.startTime != null'>",
            "  AND e.timestamp &gt;= #{query.startTime}",
            "</if>",
            "<if test='query.endTime != null'>",
            "  AND e.timestamp &lt;= #{query.endTime}",
            "</if>",
            "<if test='query.keyword != null and query.keyword != \"\"'>",
            "  AND (e.chain_name LIKE CONCAT('%', #{query.keyword}, '%')",
            "    OR e.node_name LIKE CONCAT('%', #{query.keyword}, '%')",
            "    OR e.execution_id LIKE CONCAT('%', #{query.keyword}, '%'))",
            "</if>",
            "<if test='query.eventTypes != null and query.eventTypes.size() &gt; 0'>",
            "  AND e.event_type IN",
            "  <foreach collection='query.eventTypes' item='et' open='(' separator=',' close=')'>",
            "    #{et}",
            "  </foreach>",
            "</if>",
            "GROUP BY e.execution_id",
            "<if test='query.status != null'>",
            "  HAVING MAX(CASE WHEN e.event_type IN ('CHAIN_FAILED','CHAIN_TIMEOUT') THEN 0",
            "       WHEN e.event_type = 'CHAIN_COMPLETED' THEN 1 ELSE -1 END) = #{query.status}",
            "</if>",
            "ORDER BY MIN(e.timestamp) DESC",
            "LIMIT #{limit} OFFSET #{offset}",
            "</script>"
    })
    List<ChainEventPO> selectExecutionTraces(@Param("query") EventQuery query,
                                              @Param("limit") int limit,
                                              @Param("offset") int offset);

    /**
     * 统计执行轨迹总数
     */
    @Select({
            "<script>",
            "SELECT COUNT(1) FROM (",
            "  SELECT e.execution_id",
            "  FROM chain_event e",
            "  WHERE e.execution_id IS NOT NULL",
            "<if test='query.tenantId != null'>",
            "    AND e.tenant_id = #{query.tenantId}",
            "</if>",
            "<if test='query.executionId != null and query.executionId != \"\"'>",
            "    AND e.execution_id = #{query.executionId}",
            "</if>",
            "<if test='query.chainId != null and query.chainId != \"\"'>",
            "    AND e.chain_id = #{query.chainId}",
            "</if>",
            "<if test='query.chainName != null and query.chainName != \"\"'>",
            "    AND e.chain_name LIKE CONCAT('%', #{query.chainName}, '%')",
            "</if>",
            "<if test='query.executorId != null and query.executorId != \"\"'>",
            "    AND e.executor_id = #{query.executorId}",
            "</if>",
            "<if test='query.appCode != null and query.appCode != \"\"'>",
            "    AND e.app_code = #{query.appCode}",
            "</if>",
            "<if test='query.appName != null and query.appName != \"\"'>",
            "    AND e.app_name = #{query.appName}",
            "</if>",
            "<if test='query.startTime != null'>",
            "    AND e.timestamp &gt;= #{query.startTime}",
            "</if>",
            "<if test='query.endTime != null'>",
            "    AND e.timestamp &lt;= #{query.endTime}",
            "</if>",
            "<if test='query.keyword != null and query.keyword != \"\"'>",
            "    AND (e.chain_name LIKE CONCAT('%', #{query.keyword}, '%')",
            "      OR e.node_name LIKE CONCAT('%', #{query.keyword}, '%')",
            "      OR e.execution_id LIKE CONCAT('%', #{query.keyword}, '%'))",
            "</if>",
            "<if test='query.eventTypes != null and query.eventTypes.size() &gt; 0'>",
            "    AND e.event_type IN",
            "    <foreach collection='query.eventTypes' item='et' open='(' separator=',' close=')'>",
            "      #{et}",
            "    </foreach>",
            "</if>",
            "  GROUP BY e.execution_id",
            "<if test='query.status != null'>",
            "    HAVING MAX(CASE WHEN e.event_type IN ('CHAIN_FAILED','CHAIN_TIMEOUT') THEN 0",
            "         WHEN e.event_type = 'CHAIN_COMPLETED' THEN 1 ELSE -1 END) = #{query.status}",
            "</if>",
            ") t",
            "</script>"
    })
    long countExecutionTraces(@Param("query") EventQuery query);

    /**
     * 查询指定 executionId 的所有事件（按时间升序）
     */
    @Select("SELECT * FROM chain_event WHERE execution_id = #{executionId} ORDER BY timestamp ASC")
    List<ChainEventPO> selectByExecutionId(@Param("executionId") String executionId);

    /**
     * 聚合统计：总事件数、平均耗时、成功/失败/超时数
     */
    @Select({
            "<script>",
            "SELECT",
            "  COUNT(*) AS totalCount,",
            "  AVG(CASE WHEN e.event_type IN ('CHAIN_COMPLETED','CHAIN_FAILED','CHAIN_TIMEOUT')",
            "       THEN e.cost_ms ELSE NULL END) AS avgCostMs,",
            "  SUM(CASE WHEN e.event_type = 'CHAIN_COMPLETED' THEN 1 ELSE 0 END) AS successCount,",
            "  SUM(CASE WHEN e.event_type IN ('CHAIN_FAILED','CHAIN_TIMEOUT') THEN 1 ELSE 0 END) AS failCount",
            "FROM chain_event e",
            "WHERE 1=1",
            "<if test='query.tenantId != null'>",
            "  AND e.tenant_id = #{query.tenantId}",
            "</if>",
            "<if test='query.appCode != null and query.appCode != \"\"'>",
            "  AND e.app_code = #{query.appCode}",
            "</if>",
            "<if test='query.executorId != null and query.executorId != \"\"'>",
            "  AND e.executor_id = #{query.executorId}",
            "</if>",
            "<if test='query.chainId != null and query.chainId != \"\"'>",
            "  AND e.chain_id = #{query.chainId}",
            "</if>",
            "<if test='query.startTime != null'>",
            "  AND e.timestamp &gt;= #{query.startTime}",
            "</if>",
            "<if test='query.endTime != null'>",
            "  AND e.timestamp &lt;= #{query.endTime}",
            "</if>",
            "</script>"
    })
    Map<String, Object> selectAggregatedStats(@Param("query") EventStatsQuery query);

    /**
     * 执行级统计（按 execution_id 聚合后的汇总）
     */
    @Select({
            "<script>",
            "SELECT",
            "  COUNT(*) AS executionCount,",
            "  SUM(CASE WHEN t.terminal_status = 1 THEN 1 ELSE 0 END) AS successCount,",
            "  SUM(CASE WHEN t.terminal_status = 0 THEN 1 ELSE 0 END) AS failCount,",
            "  SUM(CASE WHEN t.terminal_status = -1 THEN 1 ELSE 0 END) AS inProgressCount,",
            "  AVG(t.cost_ms) AS avgCostMs,",
            "  MAX(t.cost_ms) AS maxCostMs",
            "FROM (",
            "  SELECT e.execution_id,",
            "    MAX(CASE WHEN e.event_type IN ('CHAIN_FAILED','CHAIN_TIMEOUT') THEN 0",
            "         WHEN e.event_type = 'CHAIN_COMPLETED' THEN 1 ELSE -1 END) AS terminal_status,",
            "    MAX(CASE WHEN e.event_type IN ('CHAIN_COMPLETED','CHAIN_FAILED','CHAIN_TIMEOUT') THEN e.cost_ms END) AS cost_ms",
            "  FROM chain_event e",
            "  WHERE e.execution_id IS NOT NULL",
            "<if test='query.tenantId != null'>",
            "    AND e.tenant_id = #{query.tenantId}",
            "</if>",
            "<if test='query.appCode != null and query.appCode != \"\"'>",
            "    AND e.app_code = #{query.appCode}",
            "</if>",
            "<if test='query.appName != null and query.appName != \"\"'>",
            "    AND e.app_name = #{query.appName}",
            "</if>",
            "<if test='query.executorId != null and query.executorId != \"\"'>",
            "    AND e.executor_id = #{query.executorId}",
            "</if>",
            "<if test='query.chainId != null and query.chainId != \"\"'>",
            "    AND e.chain_id = #{query.chainId}",
            "</if>",
            "<if test='query.startTime != null'>",
            "    AND e.timestamp &gt;= #{query.startTime}",
            "</if>",
            "<if test='query.endTime != null'>",
            "    AND e.timestamp &lt;= #{query.endTime}",
            "</if>",
            "  GROUP BY e.execution_id",
            ") t",
            "</script>"
    })
    Map<String, Object> selectExecutionLevelStats(@Param("query") EventStatsQuery query);

    @Select({
            "<script>",
            "SELECT e.event_type AS eventType, COUNT(*) AS cnt",
            "FROM chain_event e",
            "WHERE 1=1",
            "<if test='query.tenantId != null'>",
            "  AND e.tenant_id = #{query.tenantId}",
            "</if>",
            "<if test='query.appCode != null and query.appCode != \"\"'>",
            "  AND e.app_code = #{query.appCode}",
            "</if>",
            "<if test='query.executorId != null and query.executorId != \"\"'>",
            "  AND e.executor_id = #{query.executorId}",
            "</if>",
            "<if test='query.chainId != null and query.chainId != \"\"'>",
            "  AND e.chain_id = #{query.chainId}",
            "</if>",
            "<if test='query.startTime != null'>",
            "  AND e.timestamp &gt;= #{query.startTime}",
            "</if>",
            "<if test='query.endTime != null'>",
            "  AND e.timestamp &lt;= #{query.endTime}",
            "</if>",
            "GROUP BY e.event_type",
            "</script>"
    })
    List<Map<String, Object>> selectTypeDistribution(@Param("query") EventStatsQuery query);

    @Select({
            "<script>",
            "SELECT t.cost_ms AS costMs FROM (",
            "  SELECT e.execution_id,",
            "    MAX(CASE WHEN e.event_type IN ('CHAIN_COMPLETED','CHAIN_FAILED','CHAIN_TIMEOUT') THEN e.cost_ms END) AS cost_ms",
            "  FROM chain_event e",
            "  WHERE e.execution_id IS NOT NULL",
            "<if test='query.tenantId != null'>",
            "    AND e.tenant_id = #{query.tenantId}",
            "</if>",
            "<if test='query.appCode != null and query.appCode != \"\"'>",
            "    AND e.app_code = #{query.appCode}",
            "</if>",
            "<if test='query.executorId != null and query.executorId != \"\"'>",
            "    AND e.executor_id = #{query.executorId}",
            "</if>",
            "<if test='query.chainId != null and query.chainId != \"\"'>",
            "    AND e.chain_id = #{query.chainId}",
            "</if>",
            "<if test='query.startTime != null'>",
            "    AND e.timestamp &gt;= #{query.startTime}",
            "</if>",
            "<if test='query.endTime != null'>",
            "    AND e.timestamp &lt;= #{query.endTime}",
            "</if>",
            "  GROUP BY e.execution_id",
            ") t WHERE t.cost_ms IS NOT NULL ORDER BY t.cost_ms",
            "</script>"
    })
    List<Long> selectExecutionCosts(@Param("query") EventStatsQuery query);

    @Select({
            "<script>",
            "SELECT",
            "  FLOOR(t.start_ts / #{bucketMs}) * #{bucketMs} AS bucketStart,",
            "  COUNT(*) AS totalCount,",
            "  SUM(CASE WHEN t.terminal_status = 1 THEN 1 ELSE 0 END) AS successCount,",
            "  SUM(CASE WHEN t.terminal_status = 0 THEN 1 ELSE 0 END) AS failCount,",
            "  AVG(t.cost_ms) AS avgCostMs",
            "FROM (",
            "  SELECT e.execution_id,",
            "    MIN(e.timestamp) AS start_ts,",
            "    MAX(CASE WHEN e.event_type IN ('CHAIN_FAILED','CHAIN_TIMEOUT') THEN 0",
            "         WHEN e.event_type = 'CHAIN_COMPLETED' THEN 1 ELSE -1 END) AS terminal_status,",
            "    MAX(CASE WHEN e.event_type IN ('CHAIN_COMPLETED','CHAIN_FAILED','CHAIN_TIMEOUT') THEN e.cost_ms END) AS cost_ms",
            "  FROM chain_event e",
            "  WHERE e.execution_id IS NOT NULL",
            "<if test='query.tenantId != null'>",
            "    AND e.tenant_id = #{query.tenantId}",
            "</if>",
            "<if test='query.appCode != null and query.appCode != \"\"'>",
            "    AND e.app_code = #{query.appCode}",
            "</if>",
            "<if test='query.executorId != null and query.executorId != \"\"'>",
            "    AND e.executor_id = #{query.executorId}",
            "</if>",
            "<if test='query.chainId != null and query.chainId != \"\"'>",
            "    AND e.chain_id = #{query.chainId}",
            "</if>",
            "<if test='query.startTime != null'>",
            "    AND e.timestamp &gt;= #{query.startTime}",
            "</if>",
            "<if test='query.endTime != null'>",
            "    AND e.timestamp &lt;= #{query.endTime}",
            "</if>",
            "  GROUP BY e.execution_id",
            ") t",
            "GROUP BY bucketStart",
            "ORDER BY bucketStart",
            "</script>"
    })
    List<Map<String, Object>> selectExecutionTrend(@Param("query") LogAnalyticsQuery query,
                                                    @Param("bucketMs") long bucketMs);

    @Select({
            "<script>",
            "SELECT",
            "  t.chain_id AS `key`,",
            "  ANY_VALUE(t.chain_name) AS name,",
            "  COUNT(*) AS totalCount,",
            "  SUM(CASE WHEN t.terminal_status = 0 THEN 1 ELSE 0 END) AS failCount,",
            "  AVG(t.cost_ms) AS avgCostMs,",
            "  MAX(t.cost_ms) AS maxCostMs",
            "FROM (",
            "  SELECT e.execution_id,",
            "    ANY_VALUE(e.chain_id) AS chain_id,",
            "    ANY_VALUE(e.chain_name) AS chain_name,",
            "    MAX(CASE WHEN e.event_type IN ('CHAIN_FAILED','CHAIN_TIMEOUT') THEN 0",
            "         WHEN e.event_type = 'CHAIN_COMPLETED' THEN 1 ELSE -1 END) AS terminal_status,",
            "    MAX(CASE WHEN e.event_type IN ('CHAIN_COMPLETED','CHAIN_FAILED','CHAIN_TIMEOUT') THEN e.cost_ms END) AS cost_ms",
            "  FROM chain_event e",
            "  WHERE e.execution_id IS NOT NULL AND e.chain_id IS NOT NULL",
            "<if test='query.tenantId != null'>",
            "    AND e.tenant_id = #{query.tenantId}",
            "</if>",
            "<if test='query.appCode != null and query.appCode != \"\"'>",
            "    AND e.app_code = #{query.appCode}",
            "</if>",
            "<if test='query.executorId != null and query.executorId != \"\"'>",
            "    AND e.executor_id = #{query.executorId}",
            "</if>",
            "<if test='query.chainId != null and query.chainId != \"\"'>",
            "    AND e.chain_id = #{query.chainId}",
            "</if>",
            "<if test='query.startTime != null'>",
            "    AND e.timestamp &gt;= #{query.startTime}",
            "</if>",
            "<if test='query.endTime != null'>",
            "    AND e.timestamp &lt;= #{query.endTime}",
            "</if>",
            "  GROUP BY e.execution_id",
            ") t",
            "GROUP BY t.chain_id",
            "<choose>",
            "  <when test='query.rankBy == \"fail\"'>",
            "    ORDER BY failCount DESC, totalCount DESC",
            "  </when>",
            "  <when test='query.rankBy == \"slow\"'>",
            "    ORDER BY avgCostMs DESC, totalCount DESC",
            "  </when>",
            "  <otherwise>",
            "    ORDER BY totalCount DESC",
            "  </otherwise>",
            "</choose>",
            "LIMIT #{query.limit}",
            "</script>"
    })
    List<Map<String, Object>> selectChainRanking(@Param("query") LogAnalyticsQuery query);

    @Select({
            "<script>",
            "SELECT",
            "  t.executor_id AS `key`,",
            "  ANY_VALUE(t.executor_id) AS name,",
            "  COUNT(*) AS totalCount,",
            "  SUM(CASE WHEN t.terminal_status = 0 THEN 1 ELSE 0 END) AS failCount,",
            "  AVG(t.cost_ms) AS avgCostMs,",
            "  MAX(t.cost_ms) AS maxCostMs",
            "FROM (",
            "  SELECT e.execution_id,",
            "    ANY_VALUE(e.executor_id) AS executor_id,",
            "    MAX(CASE WHEN e.event_type IN ('CHAIN_FAILED','CHAIN_TIMEOUT') THEN 0",
            "         WHEN e.event_type = 'CHAIN_COMPLETED' THEN 1 ELSE -1 END) AS terminal_status,",
            "    MAX(CASE WHEN e.event_type IN ('CHAIN_COMPLETED','CHAIN_FAILED','CHAIN_TIMEOUT') THEN e.cost_ms END) AS cost_ms",
            "  FROM chain_event e",
            "  WHERE e.execution_id IS NOT NULL AND e.executor_id IS NOT NULL",
            "<if test='query.tenantId != null'>",
            "    AND e.tenant_id = #{query.tenantId}",
            "</if>",
            "<if test='query.appCode != null and query.appCode != \"\"'>",
            "    AND e.app_code = #{query.appCode}",
            "</if>",
            "<if test='query.executorId != null and query.executorId != \"\"'>",
            "    AND e.executor_id = #{query.executorId}",
            "</if>",
            "<if test='query.chainId != null and query.chainId != \"\"'>",
            "    AND e.chain_id = #{query.chainId}",
            "</if>",
            "<if test='query.startTime != null'>",
            "    AND e.timestamp &gt;= #{query.startTime}",
            "</if>",
            "<if test='query.endTime != null'>",
            "    AND e.timestamp &lt;= #{query.endTime}",
            "</if>",
            "  GROUP BY e.execution_id",
            ") t",
            "GROUP BY t.executor_id",
            "<choose>",
            "  <when test='query.rankBy == \"fail\"'>",
            "    ORDER BY failCount DESC, totalCount DESC",
            "  </when>",
            "  <when test='query.rankBy == \"slow\"'>",
            "    ORDER BY avgCostMs DESC, totalCount DESC",
            "  </when>",
            "  <otherwise>",
            "    ORDER BY totalCount DESC",
            "  </otherwise>",
            "</choose>",
            "LIMIT #{query.limit}",
            "</script>"
    })
    List<Map<String, Object>> selectExecutorRanking(@Param("query") LogAnalyticsQuery query);

    @Select({
            "<script>",
            "SELECT",
            "  e.node_id AS `key`,",
            "  ANY_VALUE(e.node_name) AS name,",
            "  COUNT(*) AS totalCount,",
            "  SUM(CASE WHEN e.event_type IN ('NODE_FAILED','NODE_FALLBACK_FAILED') THEN 1 ELSE 0 END) AS failCount,",
            "  AVG(e.cost_ms) AS avgCostMs,",
            "  MAX(e.cost_ms) AS maxCostMs",
            "FROM chain_event e",
            "WHERE e.node_id IS NOT NULL AND e.node_id != ''",
            "  AND e.event_type LIKE 'NODE_%'",
            "<if test='query.tenantId != null'>",
            "  AND e.tenant_id = #{query.tenantId}",
            "</if>",
            "<if test='query.appCode != null and query.appCode != \"\"'>",
            "  AND e.app_code = #{query.appCode}",
            "</if>",
            "<if test='query.executorId != null and query.executorId != \"\"'>",
            "  AND e.executor_id = #{query.executorId}",
            "</if>",
            "<if test='query.chainId != null and query.chainId != \"\"'>",
            "  AND e.chain_id = #{query.chainId}",
            "</if>",
            "<if test='query.startTime != null'>",
            "  AND e.timestamp &gt;= #{query.startTime}",
            "</if>",
            "<if test='query.endTime != null'>",
            "  AND e.timestamp &lt;= #{query.endTime}",
            "</if>",
            "GROUP BY e.node_id",
            "<choose>",
            "  <when test='query.rankBy == \"fail\"'>",
            "    ORDER BY failCount DESC, totalCount DESC",
            "  </when>",
            "  <when test='query.rankBy == \"slow\"'>",
            "    ORDER BY avgCostMs DESC, totalCount DESC",
            "  </when>",
            "  <otherwise>",
            "    ORDER BY totalCount DESC",
            "  </otherwise>",
            "</choose>",
            "LIMIT #{query.limit}",
            "</script>"
    })
    List<Map<String, Object>> selectNodeRanking(@Param("query") LogAnalyticsQuery query);

    @Select({
            "<script>",
            "SELECT",
            "  LEFT(COALESCE(p.error_message, '未知错误'), 120) AS errorSummary,",
            "  COUNT(*) AS cnt,",
            "  MAX(e.timestamp) AS lastSeen",
            "FROM chain_event e",
            "INNER JOIN execution_payload p ON p.ref_id = e.event_id AND p.ref_type = 'CHAIN_EVENT'",
            "WHERE e.event_type IN ('CHAIN_FAILED','CHAIN_TIMEOUT','NODE_FAILED','NODE_FALLBACK_FAILED')",
            "  AND p.error_message IS NOT NULL AND p.error_message != ''",
            "<if test='query.tenantId != null'>",
            "  AND e.tenant_id = #{query.tenantId}",
            "</if>",
            "<if test='query.appCode != null and query.appCode != \"\"'>",
            "  AND e.app_code = #{query.appCode}",
            "</if>",
            "<if test='query.executorId != null and query.executorId != \"\"'>",
            "  AND e.executor_id = #{query.executorId}",
            "</if>",
            "<if test='query.chainId != null and query.chainId != \"\"'>",
            "  AND e.chain_id = #{query.chainId}",
            "</if>",
            "<if test='query.startTime != null'>",
            "  AND e.timestamp &gt;= #{query.startTime}",
            "</if>",
            "<if test='query.endTime != null'>",
            "  AND e.timestamp &lt;= #{query.endTime}",
            "</if>",
            "GROUP BY errorSummary",
            "ORDER BY cnt DESC",
            "LIMIT #{query.limit}",
            "</script>"
    })
    List<Map<String, Object>> selectFailureClusters(@Param("query") LogAnalyticsQuery query);
}
