package com.zestflow.admin.constant;

public interface ErrorCode {

    // Auth
    String INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS";
    String USER_DISABLED = "AUTH_USER_DISABLED";
    String USERNAME_EXISTS = "AUTH_USERNAME_EXISTS";
    String EMAIL_EXISTS = "AUTH_EMAIL_EXISTS";
    String USER_NOT_FOUND = "AUTH_USER_NOT_FOUND";
    String UNAUTHORIZED = "AUTH_UNAUTHORIZED";
    String PASSWORD_INCORRECT = "AUTH_PASSWORD_INCORRECT";
    String PASSWORD_SAME_AS_OLD = "AUTH_PASSWORD_SAME_AS_OLD";

    // Common
    String VALIDATION_ERROR = "VALIDATION_ERROR";
    String SERVER_ERROR = "SERVER_ERROR";

    // Application
    String MODULE_CODE_EXISTS = "MODULE_CODE_EXISTS";
    String APP_NOT_FOUND = "APP_NOT_FOUND";

    // Permission
    String PERMISSION_DENIED = "PERMISSION_DENIED";
    String SUPER_ADMIN_REQUIRED = "SUPER_ADMIN_REQUIRED";

    // Role
    String ROLE_NOT_FOUND = "ROLE_NOT_FOUND";

    // Executor
    String EXECUTOR_NOT_FOUND = "EXECUTOR_NOT_FOUND";
    String EXECUTOR_OFFLINE = "EXECUTOR_OFFLINE";

    // Schedule
    String SCHEDULE_NOT_FOUND = "SCHEDULE_NOT_FOUND";

    // Dict
    String DICT_TYPE_NOT_FOUND = "DICT_TYPE_NOT_FOUND";
    String DICT_TYPE_CODE_EXISTS = "DICT_TYPE_CODE_EXISTS";
    String DICT_DATA_NOT_FOUND = "DICT_DATA_NOT_FOUND";

    // Security
    String LOGIN_RATE_LIMITED = "LOGIN_RATE_LIMITED";

    // Tenant
    String TENANT_NOT_FOUND = "TENANT_NOT_FOUND";
    String TENANT_CODE_EXISTS = "TENANT_CODE_EXISTS";
    String TENANT_CANNOT_DELETE_SYSTEM = "TENANT_CANNOT_DELETE_SYSTEM";
    String TENANT_PROVISION_RATE_LIMITED = "TENANT_PROVISION_RATE_LIMITED";

    // Upload
    String INVALID_AVATAR_TYPE = "INVALID_AVATAR_TYPE";

    // Mail
    String INVALID_RESET_TOKEN = "AUTH_INVALID_RESET_TOKEN";
    String MAIL_SEND_FAILED = "MAIL_SEND_FAILED";
    String EMAIL_ALREADY_VERIFIED = "EMAIL_ALREADY_VERIFIED";
    String EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED";
}
